version: '3'
services:

  woa-cxfq:
    image: 'woa-cxfq-app'
    ports:
      - "8003:80"
    container_name: 'woa-cxfq'
    volumes:
      - "/data/docker_data/woa-cxfq/logs:/var/www/html/storage/logs"
#    expose:
#      - "80"
    networks:
      - 'default_net'
    
    
networks:
  default_net:
    external: true
